coverage_service: cobertura_xml
xcodeproj: CsBootcamp.xcodeproj
workspace: CsBootcamp.xcworkspace
scheme: CsBootcamp
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
ignore:
  - CsBootcampTests/*