coverage_service: cobertura_xml
xcodeproj: CsBootcamp.xcodeproj
workspace: CsBootcamp.xcworkspace
scheme: CSBootcamp
input_format: profdata
output_directory: build/Coverage/
ignore:
  - CSBootcampTests/*