disabled_rules:
# - trailing_whitespace

whitelist_rules:

opt_in_rules:
 - mark
 - private_outlet
 - vertical_whitespace

excluded:
 - Carthage
 - Pods
 - fastlane

line_length:
 warning: 143
 error: 143

private_outlet:
 severity: error

mark:
 severity: error

vertical_whitespace:
 severity: error

type_name:
 max_length: 60

variable_name:
 min_length: 3
 excluded:
   - id
   - y
   - x
