reporter: "xcode"

excluded:
  - Carthage
  - Pods
  - CSBootcampTests
  - fastlane
  - vendor

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - comments_space
  - comments_capitalized_ignore_possible_code
  - comments_capitalized_find_possible_code
  - empty_count
  - explicit_init
  - explicit_failure_calls
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_cast
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - multiple_empty_lines
  - nesting
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - sorted_imports
  - syntactic_sugar
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
 
  - mark

trailing_whitespace:
  ignores_empty_lines: true

disabled_rules:
  - missing_docs
  - todo
  
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20

function_body_length:
  warning: 80
  error: 100

file_length:
  warning: 380
  error: 420

line_length: 
  warning: 180 
  error: 200
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 35
    error: 40
  excluded:
    - id
    - url
    - key
    - x
    - y

implicitly_unwrapped_optional:
  mode: all_except_iboutlets

large_tuple:
  warning: 4
  error: 5

type_body_length:
  warning: 300
  error: 350

trailing_comma:
  mandatory_comma: true

number_separator:
  minimum_length: 8

private_outlet:
  severity: error
  allow_private_set: true

mark:
 severity: error

vertical_whitespace:
 severity: error

colon: 
  severity: error

type_name:
 max_length: 60

comma: error
empty_count: error
legacy_constant: error
legacy_constructor: error
opening_brace: error
trailing_newline: error
trailing_semicolon: error

custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  explicit_failure_calls:
      name: “Avoid asserting ‘false’”
      regex: ‘((assert|precondition)\(false)’
      message: “Use assertionFailure() or preconditionFailure() instead.”
      severity: warning
  multiple_empty_lines:
     name: "Multiple Empty Lines"
     regex: '((?:\s*\n){3,})'
     message: "There are too many line breaks"
     severity: error
