default_platform(:ios)

platform :ios do
  workspace = "CSBootcamp.xcworkspace"
  project = "CSBootcamp.xcodeproj"
  scheme = ENV["SCHEME"]
  output_name = "#{ENV["ENV_NAME"]}.ipa"

  lane :beta do
    #match
    scan
    gym
    run_firebase_app_distribution
  end

  lane :release do 
    build_number = increment_build_number()
    git_add
    git_commit(path: "*", message: "Increment new build number - #{build_number}")
    push_to_git_remote(force: true)

    create_pull_request(
      api_token: ENV["GITHUB_API_TOKEN"],
      repo: "lucabelezal/DevOpsPractices",
      title: "New beta build to Firebase App Distribution",
      body: "Build number - #{build_number}"
    )

    github_release = set_github_release(
      repository_name: "lucabelezal/DevOpsPractices",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: "Increases performance and visual improvements!",
      tag_name: "v1.0.0(#{build_number})",
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "develop"
    )
  end

  lane :run_firebase_app_distribution do
    firebase_app_distribution(
      googleservice_info_plist_path: ENV["PATH_INFOPLIST"],
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      ipa_path: "./.fastlane/output/#{output_name}",
      testers: "lucabelezal@gmail.com",
      release_notes: "Lots of amazing new features to test out!",
      debug: true
    )
  end

  lane :run_tests_app do
    run_tests(
      workspace: $workspace,
      devices: ["iPhone 11"],
      reinstall_app: true,
      code_coverage: true,
      derived_data_path: "./DerivedData",
      scheme: $scheme
  )
  end

  lane :run_build_app do
    build_app(workspace: $workspace, scheme: $scheme, skip_codesigning: true, skip_archive: true)
  end

  lane :run_snapshot do
    snapshot
  end

  lane :run_swiftlint do
    swiftlint(
      output_file:"./reports/swiftlint.json",
      reporter:"json" ,
      ignore_exit_status:"true"
    )
  end

  lane :run_slather do
    slather(
      sonarqube_xml: true,
      build_directory: "./DerivedData",
      input_format: "profdata",
      output_directory: "./reports",
      binary_basename: $scheme,
      scheme: $scheme,
      proj: $project,
      workspace: $workspace
    )
  end
  
  lane :run_codecov_reporter do
    codecov_reporter(
      token: ENV["CODECOV_TOKEN"]
    )
  end

  lane :run_sonar do
    sonar(
      sonar_login: ENV["SONAR_TOKEN"],
      project_key: "lucabelezal_DevOpsPractices",
      sonar_organization: "skeleton",
      project_name: $scheme,
      sources_path: File.expand_path("../CSBootcamp"),
      sonar_url: "https://sonarcloud.io"
    )
  end
end


