name: CI

on:
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*

jobs:
  build:
    name: Run Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      - name: Install Dependencies
        run: |
          brew install swiftlint
          brew install rbenv
          brew install rbenv-gemset
          rbenv global 2.6.3
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
          gem env home
          ruby -v
          gem install bundle
          bundle install
          bundle exec pod install
      - name: Xcode Build
        run: |
          set -o pipefail xcodebuild build -workspace CsBootcamp.xcworkspace -scheme 'CsBootcamp' CODE_SIGNING_ALLOWED=NO | xcpretty

  test:
    name: Run Tests
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Fetch all branches
        run: |
          git fetch --prune --unshallow
      - name: Run Tests
        run: |
          set -o pipefail
          gem install bundler:2.1.4
          bundle install
          bundle exec pod install
          bundle exec fastlane tests
      - name: Convert Logs
        run: |
          scripts/xcov-to-sonarqube-generic.sh build/Logs/Test/Run-covidwatch-ios-* > coverage.xml
      - name: Install SonarCloud
        run: |
          export SONAR_SCANNER_VERSION=4.2.0.1873
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-macosx.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - name: Run SonarQube
        env:
          SONARCLOUD_LOGIN_KEY: ${{ secrets.SONARCLOUD_LOGIN_KEY }}
        run: |
          export SONAR_SCANNER_VERSION=4.2.0.1873
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-macosx
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          export SONAR_SCANNER_OPTS="-server"
          sonar-scanner \
          -Dsonar.organization=covid19risk \
          -Dsonar.projectKey=covid19risk_covidwatch-ios \
          -Dsonar.sources="CsBootcamp" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONARCLOUD_LOGIN_KEY \
          -Dsonar.branch.name=develop \
          -Dsonar.c.file.suffixes=- \
          -Dsonar.cpp.file.suffixes=- \
          -Dsonar.objc.file.suffixes=- \
          -Dsonar.coverageReportPaths=coverage.xml
