name: Scan PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
  
    - name: Gem cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

    - name: Pods cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        podfile-path: ./Podfile.lock

    - name: Install Bundle Dependencies
      run: |
        set -o pipefail
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf Pods/
        rm -rf Podfile.lock
        rm -rf Gemfile.lock
        gem install bundler
        bundle install

    - name: Install Pod Dependencies
      run: |
        bundle exec pod install
      
    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild -version
        xcodebuild -workspace 'CSBootcamp.xcworkspace' \
        -scheme CSBootcamp \
        -enableCodeCoverage YES clean build test \
        -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' \
        | xcpretty && exit ${PIPESTATUS[0]}

    - name: Run SwiftLint
      run: |
        mkdir -p build/Lint/
        fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

