name: Scan PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    env:
      sonarToken: ${{ secrets.SONAR_TOKEN }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Tools
      run: |
        brew install sonar-scanner
        brew install swiftlint
        gem install slather

    - name: Check Dependencie Cache
      uses: actions/cache@v2
      id: pods-cache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Install Dependencies
      if: steps.pods-cache.outputs.cache-hit != 'true'
      run: |
        bundle install
        bundle exec pod install

    - name: Build and test
      run: |
        xcodebuild -version
        xcodebuild build test -workspace "${workspace}" -scheme "${scheme}" ${params} -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
      env:
        workspace: 'CSBootcamp.xcworkspace'
        params: '-derivedDataPath ./DerivedData -enableCodeCoverage YES'
        scheme: 'CSBootcamp'
        destination: 'platform=iOS Simulator,name=iPhone 11,OS=latest'
        DEVELOPER_DIR: ${{ matrix.xcode }}

    - name: Slather
      run: |
        slather coverage --sonarqube-xml ${params} ${workspace}
      env:
        workspace: 'CSBootcamp.xcworkspace'
        params: '-scheme CSBootcamp --build-directory ./DerivedData --output-directory ./reports'

    - name: SwiftLint
      run: |
        fastlane run swiftlint output_file:"./reports/swiftlint.json" reporter:"json" ignore_exit_status:"true"

    - name: Run Sonar
      if: ${{ env.sonarToken != 0 }}
      run: |
        sonar-scanner -X -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
